src/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'(?P<pk>\d+)/$', views.detail, name='detail'),
	url(r'(?P<tag>[\w-]+)/$', views.category, name='category'),
]

src/fd_portfolio/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^contact/$', 'fd_portfolio.views.contact', name='contact'),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio', app_name='portfolio')),
    url(r'^services/$', views.services, name='services'),
    url(r'^team/$', views.team, name='team'),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'fd_portfolio.views.index', name='home'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/layout/_footer.html
{% load static from staticfiles %}
<!-- ============================================================= FOOTER ============================================================= -->
<footer class="dark-bg">
	<div class="container inner">
		<div class="row">
			
			<div class="col-md-3 col-sm-6 inner">
				<h4>Who we are</h4>
				<a href="{% url 'home' %}"><img class="logo img-intext" src="{% static 'images/logo-white.svg' %}" alt=""></a>
				<p>Magnis modipsae voloratati andigen daepeditem quiate re porem que aut labor. Laceaque eictemperum quiae sitiorem rest non restibusaes maio es dem tumquam.</p>
				<a href="{% url 'team' %}" class="txt-btn">More about us</a>
			</div><!-- /.col -->
			
			{% if recent_four %}
			<div class="col-md-3 col-sm-6 inner">
				<h4>Latest posts</h4>
				
				<div class="row thumbs gap-xs">

					{% for post in recent_four %}								
					<div class="col-xs-6 thumb">
						<figure class="icon-overlay icn-link">
							<a href="{% url 'blog:detail' post.pk %}">
								<figcaption class="text-overlay">
									<div class="info">
										<p>{{ post.title }}</p>
									</div><!-- /.info -->
								</figcaption>
								{% if post.images.first %}
									<img src="{{ MEDIA_URL }}{{ post.images.first.thumb }}" alt="{{ post.images.first.name }}">
								{% else %}
									<img src="{% static 'images/art/work16.jpg' %}">
								{% endif %}
							</a>
						</figure>
					</div><!-- /.thumb -->
					{% endfor %}
					
				</div><!-- /.row -->
			</div><!-- /.col -->
			{% endif %}
			
			
			<div class="col-md-3 col-sm-6 inner">
				<h4>Get In Touch</h4>
				<p>Doloreiur quia commolu ptatemp dolupta oreprerum tibusam eumenis et consent accullignis dentibea autem inisita.</p>
				<ul class="contacts">
					<li><a href="https://www.google.com/maps/@29.5535645,-98.4791917,12.04z" target="_blank"><i class="icon-location contact"></i> San Antonio, TX 78232</a></li>
					<li><a href="tel:+18005551234"><i class="icon-mobile contact"></i> (800) 555-1234</a></li>
					<li><a href="#"><a href="{% url 'contact' %}"><i class="icon-mail-1 contact"></i> test@flattdesign.com</a></li>
				</ul><!-- /.contacts -->
			</div><!-- /.col -->
			
			{% if featured_post %}
			<div class="col-md-3 col-sm-6 inner">
				<h4>Figure Out What Goes Here</h4>
				<figure>
					<div class="icon-overlay icn-link">
						{% if featured_post.images.first %}
						<a href="{% url 'blog:detail' pk=featured_post.id %}"><img src="{{ MEDIA_URL }}{{ featured_post.images.first.image }}" alt="{{ featured_post.images.first.name }}"></a>
						{% else %}
						<a href="{% url 'blog:detail' pk=featured_post.id %}"><img src="{% static 'images/art/work02.jpg' %}" alt=""></a>
						{% endif %}
					</div>
					<figcaption>
						<p>{{ featured_post.tagline }}</p>
						<a href="{% url 'blog:detail' pk=featured_post.pk %}" class="btn">Read More</a>
					</figcaption>
				</figure>
			</div>
			{% endif %}
			
		</div><!-- /.row --> 
	</div><!-- .container -->
  
	<div class="footer-bottom">
		<div class="container inner">
			<p class="pull-left">© {% now 'Y' %} FLATT DESIGN. All rights reserved.</p>
			<ul class="footer-menu pull-right">
				<li><a href="{% url 'home' %}">Home</a></li>
				<li><a href="{% url 'portfolio:index' %}">Portfolio</a></li>
				<li><a href="{% url 'blog:index' %}">Blog</a></li>
				<li><a href="{% url 'services' %}">Services</a></li>
				<li><a href="{% url 'team' %}">Team</a></li>
				<li><a href="{% url 'contact' %}">Contact</a></li>
			</ul><!-- .footer-menu -->
		</div><!-- .container -->
	</div><!-- .footer-bottom -->
</footer>

<!-- ============================================================= FOOTER : END ============================================================= -->

src/templates/layout/_header.html
{% load static from staticfiles %}
<header>
	<div class="navbar">
		
		<div class="navbar-header">
			<div class="container">
				
				<ul class="info pull-left">
					<li><a href="{% url 'contact' %}"><i class="icon-mail-1 contact"></i> test@flattdesign.com</a></li>
					<li><a href="tel:+18005551234"><i class="icon-mobile contact"></i> (800) 555-1234</a></li>
				</ul><!-- /.info -->
				
				<ul class="social pull-right">
					<li><a href="https://www.facebook.com/tc.flatt" target="_blank"><i class="icon-s-facebook"></i></a></li>
					<!-- <li><a href="#"><i class="icon-s-gplus"></i></a></li> -->
					<li><a href="https://twitter.com/FlattDesign" target="_blank"><i class="icon-s-twitter"></i></a></li>
					<li><a href="https://www.pinterest.com/flattdesign/" target="_blank"><i class="icon-s-pinterest"></i></a></li>
					<!-- <li><a href="#"><i class="icon-s-behance"></i></a></li>
					<li><a href="#"><i class="icon-s-dribbble"></i></a></li> -->
				</ul><!-- /.social -->
				
				<!-- ============================================================= LOGO MOBILE ============================================================= -->
				
				<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.svg' %}" class="logo" alt=""></a>
				
				<!-- ============================================================= LOGO MOBILE : END ============================================================= -->
				
				<a class="navbar-toggle btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>
				
			</div><!-- /.container -->
		</div><!-- /.navbar-header -->
		
		<div class="yamm">
			<div class="navbar-collapse collapse">
				<div class="container">
					
					<!-- ============================================================= LOGO ============================================================= -->
					
					<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.svg' %}" class="logo" alt=""></a>
					
					<!-- ============================================================= LOGO : END ============================================================= -->
					
					
					<!-- ============================================================= MAIN NAVIGATION ============================================================= -->
					
					<ul class="nav navbar-nav">
						
						<li>
							<a href="{% url 'home' %}">Home</a>
						</li>
						
						<li class="dropdown">
							<a href="#" class="dropdown-toggle">About</a>
							
							<ul class="dropdown-menu">
								<li><a href="{% url 'services' %}">Our Services</a></li>
								<li><a href="{% url 'team' %}">About Our Team</a></li>
							</ul><!-- /.dropdown-menu -->
						</li><!-- /.dropdown -->
						
						<li>
							<a href="{% url 'blog:index' %}">Blog</a>
						</li>
						
						<li>
							<a href="{% url 'portfolio:index' %}">Portfolio</a>
						</li>
						
						<!-- ============================================================= MEGA MENU ============================================================= -->
						
						<li class="dropdown yamm-fullwidth">
							<a href="#" class="dropdown-toggle">Latest</a>
							
							<ul class="dropdown-menu yamm-dropdown-menu">
								<li>
									<div class="yamm-content row">
									
										{% if featured_post %}
										<div class="col-sm-3 inner">
											<h4>Spotlight</h4>
											<figure>
												<div class="icon-overlay icn-link">
													{% if featured_post.images.first %}
													<a href="{% url 'blog:detail' pk=featured_post.id %}"><img src="{{ MEDIA_URL }}{{ featured_post.images.first.image }}" alt="{{ featured_post.images.first.name }}"></a>
													{% else %}
													<a href="{% url 'blog:detail' pk=featured_post.id %}"><img src="{% static 'images/art/work02.jpg' %}" alt=""></a>
													{% endif %}
												</div>
												<figcaption>
													<p>{{ featured_post.tagline }}</p>
													<a href="{% url 'blog:detail' pk=featured_post.pk %}" class="btn">Read More</a>
												</figcaption>
											</figure>
										</div><!-- /.col -->
										{% endif %}
										
										{% if latest_links %}
										<div class="col-sm-3 inner">
											<h4>Latest Links</h4>
											
											<ul class="circled">
												
												{% for link in latest_links %}
												<li><a href="{{ link.link_url }}" target="_blank">{{ link.link_text }}</a></li>
												{% endfor %}
											</ul><!-- /.circled -->
										</div><!-- /.col -->
										{% endif %}
										
										{% if nav_latest_projects %}
										<div class="col-sm-3 inner">
											<h4>Latest Work</h4>
											
											<div class="row thumbs gap-xs">
												{% for project in nav_latest_projects %}
												<div class="col-xs-6 thumb">
													<figure class="icon-overlay icn-link">
														<a href="{% url 'portfolio:detail' pk=project.pk %}"><img src="{{ MEDIA_URL }}{{ project.images.first.thumb }}" alt="{{ project.images.first.name }}"></a>
													</figure>
												</div><!-- /.thumb -->
												{% endfor %}
											</div><!-- /.row -->
										</div><!-- /.col -->
										{% endif %}
										
										<div class="col-sm-3 inner">
											<h4>About Us</h4>
											<p>Voluptat ibusaped molorporro consequ idustibus. Reressi morum ut dolessiti tem nihicid ernatum, coria volore non pro officat ut autem accaborem conet. Omnis peribus qui dolent praeperrum coria.</p>
											<a href="{% url 'team' %}" class="btn">Meet Our Team</a>
										</div><!-- /.col -->
										
									</div><!-- /.yamm-content -->
								</li>
							</ul><!-- /.yamm-dropdown-menu -->
						</li><!-- /.yamm-fullwidth -->
						
						<!-- ============================================================= MEGA MENU : END ============================================================= -->
						
						<li>
							<a href="{% url 'contact' %}">Contact</a>
						</li>
						
						<li class="dropdown pull-right searchbox">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i></a>
									  
							<div class="dropdown-menu">
								<form id="search" class="navbar-form search" role="search">
									<input type="search" class="form-control" placeholder="Type to search">
									<button type="submit" class="btn btn-default btn-submit icon-right-open"></button>
								</form>
							</div><!-- /.dropdown-menu -->
						</li><!-- /.searchbox -->
						
					</ul><!-- /.nav -->
					
					<!-- ============================================================= MAIN NAVIGATION : END ============================================================= -->
					
				</div><!-- /.container -->
			</div><!-- /.navbar-collapse -->
		</div><!-- /.yamm -->
	</div><!-- /.navbar -->
</header>

<!-- ============================================================= HEADER : END ============================================================= -->

src/templates/layout/_links.html
{% load static from staticfiles %}

<!-- Core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet" data-skrollr-stylesheet>

<!-- Customizable CSS -->
<link href="{% static 'css/orange.css' %}" rel="stylesheet" title="Color">
<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
<link href="{% static 'css/owl.transitions.css' %}" rel="stylesheet">
<link href="{% static 'css/aos.css' %}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{% static 'css/custom.css' %}" rel="stylesheet">

<!-- Fonts -->
<link href="http://fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet">

<!-- Icons/Glyphs -->
<link href="{% static 'fonts/fontello.css' %}" rel="stylesheet">

<!-- Favicon -->
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
<!--[if lt IE 9]>
	<script src="{% static 'js/html5shiv.js' %}"></script>
	<script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->

src/templates/layout/_meta.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<meta name="description" content="Flatt Design: Web Design and Development in San Antonio, Texas.">
<meta name="author" content="Travis C. Flatt">

src/templates/layout/_scripts.html
{% load static from staticfiles %}

<!-- JavaScripts placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.easytabs.min.js' %}"></script>
<script src="{% static 'js/viewport-units-buggyfill.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

src/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	<!-- Meta -->
		{% include 'layout/_meta.html' %}

		<title>Flatt Design - {% block title %}{% endblock title %}</title>
		
		{% include 'layout/_links.html' %}
		
		
		{% block cssextra %}
		{% endblock cssextra %}
	</head>
	<body>

		{% include 'layout/_header.html' %}

		<!-- ============================================================= MAIN ============================================================= -->
		{% block content %}
		{% endblock content %}

		<!-- ======================================================= MAIN : END ============================================================= -->
		
		{% include 'layout/_footer.html' %}
		

		{% include 'layout/_scripts.html' %}

		{% block jsextra %}
		{% endblock jsextra %}
	</body>
</html>